"""init_threat_table

Revision ID: 38140ae77f12
Revises: 
Create Date: 2026-04-09 00:47:55.819384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38140ae77f12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source_ip', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('threat_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_events_id'), 'threat_events', ['id'], unique=False)
    op.create_index(op.f('ix_threat_events_source_ip'), 'threat_events', ['source_ip'], unique=False)
    op.create_index(op.f('ix_threat_events_threat_type'), 'threat_events', ['threat_type'], unique=False)
    op.create_index(op.f('ix_threat_events_timestamp'), 'threat_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_events_timestamp'), table_name='threat_events')
    op.drop_index(op.f('ix_threat_events_threat_type'), table_name='threat_events')
    op.drop_index(op.f('ix_threat_events_source_ip'), table_name='threat_events')
    op.drop_index(op.f('ix_threat_events_id'), table_name='threat_events')
    op.drop_table('threat_events')
    # ### end Alembic commands ###
